#ifndef STAN_MATH_OPENCL_REV_HPP
#define STAN_MATH_OPENCL_REV_HPP
#ifdef STAN_OPENCL

#include <opencl/prim.hpp>
#include <opencl/rev/append_col.hpp>
#include <opencl/rev/append_row.hpp>
#include <opencl/rev/as_column_vector_or_scalar.hpp>
#include <opencl/rev/acos.hpp>
#include <opencl/rev/acosh.hpp>
#include <opencl/rev/add.hpp>
#include <opencl/rev/add_diag.hpp>
#include <opencl/rev/adjoint_results.hpp>
#include <opencl/rev/arena_matrix_cl.hpp>
#include <opencl/rev/arena_type.hpp>
#include <opencl/rev/asin.hpp>
#include <opencl/rev/asinh.hpp>
#include <opencl/rev/atan.hpp>
#include <opencl/rev/atanh.hpp>
#include <opencl/rev/beta.hpp>
#include <opencl/rev/block.hpp>
#include <opencl/rev/cbrt.hpp>
#include <opencl/rev/ceil.hpp>
#include <opencl/rev/cholesky_decompose.hpp>
#include <opencl/rev/columns_dot_product.hpp>
#include <opencl/rev/columns_dot_self.hpp>
#include <opencl/rev/copy.hpp>
#include <opencl/rev/cos.hpp>
#include <opencl/rev/cosh.hpp>
#include <opencl/rev/crossprod.hpp>
#include <opencl/rev/cumulative_sum.hpp>
#include <opencl/rev/diag_matrix.hpp>
#include <opencl/rev/diag_pre_multiply.hpp>
#include <opencl/rev/diag_post_multiply.hpp>
#include <opencl/rev/diagonal.hpp>
#include <opencl/rev/digamma.hpp>
#include <opencl/rev/divide.hpp>
#include <opencl/rev/dot_product.hpp>
#include <opencl/rev/dot_self.hpp>
#include <opencl/rev/elt_divide.hpp>
#include <opencl/rev/elt_multiply.hpp>
#include <opencl/rev/erf.hpp>
#include <opencl/rev/erfc.hpp>
#include <opencl/rev/exp.hpp>
#include <opencl/rev/exp2.hpp>
#include <opencl/rev/expm1.hpp>
#include <opencl/rev/fabs.hpp>
#include <opencl/rev/fdim.hpp>
#include <opencl/rev/floor.hpp>
#include <opencl/rev/fmax.hpp>
#include <opencl/rev/fmin.hpp>
#include <opencl/rev/fmod.hpp>
#include <opencl/rev/hypot.hpp>
#include <opencl/rev/inv.hpp>
#include <opencl/rev/inv_cloglog.hpp>
#include <opencl/rev/inv_logit.hpp>
#include <opencl/rev/inv_Phi.hpp>
#include <opencl/rev/inv_sqrt.hpp>
#include <opencl/rev/inv_square.hpp>
#include <opencl/rev/lb_constrain.hpp>
#include <opencl/rev/lbeta.hpp>
#include <opencl/rev/ldexp.hpp>
#include <opencl/rev/lgamma.hpp>
#include <opencl/rev/lmultiply.hpp>
#include <opencl/rev/log.hpp>
#include <opencl/rev/log10.hpp>
#include <opencl/rev/log1m.hpp>
#include <opencl/rev/log1p.hpp>
#include <opencl/rev/log2.hpp>
#include <opencl/rev/logit.hpp>
#include <opencl/rev/log1m_exp.hpp>
#include <opencl/rev/log1p_exp.hpp>
#include <opencl/rev/log_inv_logit.hpp>
#include <opencl/rev/log1m_inv_logit.hpp>
#include <opencl/rev/log_inv_logit_diff.hpp>
#include <opencl/rev/log_diff_exp.hpp>
#include <opencl/rev/log_softmax.hpp>
#include <opencl/rev/log_sum_exp.hpp>
#include <opencl/rev/lub_constrain.hpp>
#include <opencl/rev/matrix_power.hpp>
#include <opencl/rev/mdivide_left_tri_low.hpp>
#include <opencl/rev/mdivide_right_tri_low.hpp>
#include <opencl/rev/multiply.hpp>
#include <opencl/rev/multiply_log.hpp>
#include <opencl/rev/multiply_lower_tri_self_transpose.hpp>
#include <opencl/rev/offset_multiplier_constrain.hpp>
#include <opencl/rev/operands_and_partials.hpp>
#include <opencl/rev/operator_unary_minus.hpp>
#include <opencl/rev/operator_unary_plus.hpp>
#include <opencl/rev/Phi.hpp>
#include <opencl/rev/Phi_approx.hpp>
#include <opencl/rev/pow.hpp>
#include <opencl/rev/prod.hpp>
#include <opencl/rev/rep_matrix.hpp>
#include <opencl/rev/reverse.hpp>
#include <opencl/rev/round.hpp>
#include <opencl/rev/rows_dot_product.hpp>
#include <opencl/rev/rows_dot_self.hpp>
#include <opencl/rev/sd.hpp>
#include <opencl/rev/sin.hpp>
#include <opencl/rev/sinh.hpp>
#include <opencl/rev/softmax.hpp>
#include <opencl/rev/sqrt.hpp>
#include <opencl/rev/square.hpp>
#include <opencl/rev/squared_distance.hpp>
#include <opencl/rev/subtract.hpp>
#include <opencl/rev/symmetrize_from_lower_tri.hpp>
#include <opencl/rev/symmetrize_from_upper_tri.hpp>
#include <opencl/rev/sum.hpp>
#include <opencl/rev/tan.hpp>
#include <opencl/rev/tanh.hpp>
#include <opencl/rev/tcrossprod.hpp>
#include <opencl/rev/tgamma.hpp>
#include <opencl/rev/to_arena.hpp>
#include <opencl/rev/to_matrix.hpp>
#include <opencl/rev/trace.hpp>
#include <opencl/rev/transpose.hpp>
#include <opencl/rev/trunc.hpp>
#include <opencl/rev/ub_constrain.hpp>
#include <opencl/rev/unit_vector_constrain.hpp>
#include <opencl/rev/variance.hpp>
#include <stan/math/rev.hpp>

#endif
#endif
