on:
  push:
    branches: [main, master, chk]
  pull_request:
    branches: [main, master]

name: R-CMD-check-special

jobs:
  sanitizers-and-valgrind:
    runs-on: ubuntu-latest
    name: ${{ matrix.config.name }}
    container:
      image: ${{ matrix.config.container }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - { label: "clang-asan",
              name: "clang-asan",
              container: "ghcr.io/r-hub/containers/clang-asan:latest"}
          - { label: "gcc-asan",
              name: "gcc-asan",
              container: "ghcr.io/r-hub/containers/gcc-asan:latest"}
          - { label: "valgrind",
              name: "valgrind",
              container: "ghcr.io/r-hub/containers/valgrind:latest"}
          - { label: "rchk",
              name: "rchk",
              container: "ghcr.io/r-hub/containers/rchk:latest"}
          - { label: "c23",
              name: "c23",
              container: "ghcr.io/r-hub/containers/c23:latest"}
          - { label: "gcc15",
              name: "gcc15",
              container: "ghcr.io/r-hub/containers/gcc15:latest"}
          - { label: "clang20",
              name: "clang20",
              container: "ghcr.io/r-hub/containers/clang20:latest"}
          - { label: "lto",
              name: "lto",
              container: "ghcr.io/r-hub/containers/lto:latest"}

    env:
      MAKEFLAGS: -j4
    steps:
      - uses: r-hub/actions/checkout@main
        with:
          submodules: true
      - uses: r-hub/actions/platform-info@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          job-config: ${{ toJson(matrix.config) }}
      - name: Install awk for gcc15
        if: matrix.config.label == 'gcc15'
        run: |
          dnf update -y && dnf install -y awk
      - uses: r-hub/actions/setup-deps@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          job-config: ${{ toJson(matrix.config) }}

      - name: Install package dependencies
        if: matrix.config.label == 'rchk'
        shell: Rscript {0}
        run: install.packages("RcppParallel", type = "source", repos = "https://cloud.r-project.org")

      - uses: r-hub/actions/run-check@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          job-config: ${{ toJson(matrix.config) }}
